version: '3.8'
services:
  mongo:
    image: mongo:4.2.23-rc1-bionic
    volumes:
      - 'mongo:/bitnami/mongodb'
    ports: 
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_DATABASE="zkpad-dev"

  mysql:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
  minio:
    image: 'docker.io/bitnami/minio:2020-debian-10'
    ports:
      - '9000:9000'
    environment:
      - MINIO_API_CORS_ALLOW_ORIGIN=*
      - MINIO_DEFAULT_BUCKETS=zkpad
    volumes:
      - ./data:/data
volumes:
  mysql:
    driver: local
  mongo:
    driver: local
